#config_version=6

# This is the mode definition for attract mode. 

# The following is the mode settings data
mode_settings:
  selectable_items:
    - title
#    - machineCredits
    - scores
    - lastGame
  next_item_events: sRightFlipperButton_active, timer_attract_carousel_timer_complete
  previous_item_events: sLeftFlipperButton_active

# The following defines what slides will be played in this mode
slide_player:

  # Slides are defined as follows: 
  # Event used to call Slide: Slide to be Shown
  mode_attract_started: attract

# The following defines what sounds will be played in this mode
sound_player:

  # Sounds will be called in the following way:
  # Event to Call Music:
  #   Song File Title:
  #     bus: Godot Media Bus
  mode_attract_started:
    Inspired:
      bus: music

# The following defines the timers in this mode
timers:

  # Timers are named and defined as such:
  # Name of Timer:
  #   end_value: Final Value in Timer
  #   tick_interval: Length of Tick
  #   start_running: Should the timer be running immediately/when enabled
  #   control_events:
  #     - event: Name of Event to Call Timer Control Event
  #       action: Type of Control Event to be Peformed (stop/restart)
  attract_carousel_timer:
    end_value: 1
    tick_interval: 5s
    start_running: true
    control_events:
      - event: carousel_item_highlighted
        action: restart
      - event: flipper_cradle
        action: stop
      - event: flipper_cradle_release
        action: restart

# The following contains the definitions for shows to be played in this mode
show_player:

  # Show cues are based on events being called, they are defined as such:
  # Event to Call Show:
  #   Name of Show To Play:
  #     speed: Speed of Show Playback
  #     show_tokens:
  #       color: Color to use for Show
  #       lights: Lights to be Used for This Show
  mode_attract_started:
    flash:
      speed: 2
      show_tokens:
        lights: startLight

# Comment Version Tracking 0.1.1