#config_version=6

mode:
  start_events: start-mode-flipperlanes-base
  stop_events: stop-mode-flipperlanes-base, ball_will_end
  priority: 1500

shots:
  leftInnerLane:
    switch: sLeftInlane
  leftOuterLane:
    switch: sLeftOutlane
  rightInnerLane:
    switch: sRightInlane
  rightOuterLane:
    switch: sRightOutlane

shot_groups:
  lower_lanes:
    shots: leftInnerLane, leftOuterLane, rightInnerLane,rightOuterLane