#config_version=6

mode:
  start_events: start-mode-potionSelection
  stop_events: stop-mode-potionSelection
  priority: 620

show_player:
  mode_potionSelection_started:
    shotArrowForward:
      speed: 2
      show_tokens:
        tip: potionSelectionTipInsert
        center: potionSelectionCenterInsert
        base: potionSelectionBaseInsert
        color: 8000FF