#config_version=6

coils:
  cBallTroughEject:
    number: pio1-2
    default_pulse_ms: 25
  cLeftFlipperPower:
    number: pio1-1
    default_pulse_ms: 40
  cLeftFlipperHold:
    number: pio1-0
    allow_enable: true
  cRightFlipperPower:
    number: pio1-7
    default_pulse_ms: 40
  cRightFlipperHold:
    number: pio1-6
    allow_enable: true
  cLeftSling:
    number: pio1-4
    default_pulse_ms: 15
    platform_settings:
      recycle_ms: 40
  cRightSling:
    number: pio1-5
    default_pulse_ms: 15
    platform_settings:
      recycle_ms: 40
  cAutoPlunger:
    number: pio1-3
  cSpringPopPost:
    number: pio2-2
  cSpring3Reset:
    number: pio2-0
    default_pulse_ms: 25
  cSpring3Knock:
    number: pio2-1
  cSpring1Reset:
    number: pio2-3
    default_pulse_ms: 15