#config_version=6

hardware:
    platform: fast

fast:
    

    aud:
        port: auto
        main_amp_enabled: true

        main_steps: 20

        default_main_volume: 32

        persist_volume_settings: true

        max_hw_volume_main: 63

        main_levels_list: None