#config_version=6

switches:
    sLeftFlipperEOS:
        number: 
    sRightFlipperEOS:
        number: 
    sPlungerLane:
        number: 
    sLeftFlipperButton:
        number: 
    sRightFlipperButton:
        number: 
    sRightSlingUpper:
        number: 
    sRightSlingLower:
        number: 
    sLeftSlingUpper:
        number: 
    sLeftSlingLower:
        number: 
    sBallJam:
        number: 
    sBall1:
        number: 
    sBall2:
        number: 
    sBall3:
        number: 
    sBall4:
        number: 
    sBall5:
        number: 
    sBall6:
        number: 
    sStartButton:
        number: 
        tags: start
    sPlungerButton:
        number: 
    sSinglePopTarget:
        number: 
    sCreditBackButton:
        number: 
        tags: service_esc
    sLeftMinus:
        number: 
        tags: service_down
    sRightPlus:
        number: 
        tags: service_up
    sMenuSelectButton:
        number: 
        tags: service_enter