#config_version=6

modes:
  - service
  - base
  - bonus
  - high_score
  - flipperlanes_base
  - global
  - potionQualifier
  - potionSelection
  - cauldronManager
  - targetManager
  - ballSaveManager
  - springManager