#config_version=6

switches:
  sPlungerLane:
    number: pio1-0
    platform_settings:
      debounce_open: 5ms
      debounce_close: 20ms
  sBallJam:
    number: pio1-1
    type: NC
  sBall1:
    number: pio1-2
    type: NC
  sBall2:
    number: pio1-3
  sBall3:
    number: pio1-4
  sBall4:
    number: pio1-5
  sBall5:
    number: pio1-6
  sBall6:
    number: pio1-7
  sRightOutlane:
    number: pio1-11
  sRightInlane:
    number: pio1-12
  sRightSlingUpper:
    number: pio1-13
    debounce: quick
  sRightSlingLower:
    number: pio1-14
    debounce: quick
  sRightFlipperEOS:
    number: pio1-15
    type: NC
    debounce: quick
  sLeftOutlane:
    number: pio1-27
  sLeftInlane:
    number: pio1-28
  sLeftSlingUpper:
    number: pio1-29
    debounce: quick
  sLeftSlingLower:
    number: pio1-30       
    debounce: quick
  sLeftFlipperEOS:
    number: pio1-31
    type: NC
    debounce: quick
  sCreditBackButton:
    number: cabio-0
    tags: service_esc
  sLeftMinus:
    number: cabio-1
    tags: service_down
  sRightPlus:
    number: cabio-2
    tags: service_up
  sMenuSelectButton:
    number: cabio-3
    tags: service_enter
  sInterlock:
    number: cabio-7
  sLeftFlipperButton:
    number: cabio-8
    debounce: quick
  sStartButton:
    number: cabio-9
    tags: start
  sRightFlipperButton:
    number: cabio-16
    debounce: quick