#config_version=6

hardware:
    platform: fast

fast:
    net:
        controller: neuron
        port: /dev/ttyAMA2
        io_loop:
            pio1:
                model: FP-I/O-3208
                order: 1
            pio2:
                model: FP-I/O-3208
                order: 2
            cabio:
                model: FP-I/O-0024
                order: 3
        baud: 921600
        debug: false
        watchdog: 1s
        default_quick_debounce_open: 2ms
        default_quick_debounce_close: 2ms
        default_normal_debounce_open: 4ms
        default_normal_debounce_close: 4ms

switches:
    sLeftFlipperEOS:
        number: pio1-31
        type: NC
        debounce: quick
    sRightFlipperEOS:
        number: pio1-15
        type: NC
        debounce: quick
    sPlungerLane:
        number: pio1-0
        platform_settings:
            debounce_open: 5ms
            debounce_close: 20ms
    sLeftFlipperButton:
        number: cabio-8
        debounce: quick
    sRightFlipperButton:
        number: cabio-16
        debounce: quick
    sRightSlingUpper:
        number: pio1-13
    sRightSlingLower:
        number: pio1-14
    sLeftSlingUpper:
        number: pio1-29
        debounce: quick
    sLeftSlingLower:
        number: pio1-30       
        debounce: quick
    sBallJam:
        number: pio1-2
        type: NC
    sBall1:
        number: pio1-1
        type: NC
    sBall2:
        number: pio1-3
    sBall3:
        number: pio1-4
    sBall4:
        number: pio1-5
    sBall5:
        number: pio1-6
    sBall6:
        number: pio1-7
    s1PopTarget:
        number: pio2-28
        tags: playfield_active
    sStartButton:
        number: cabio-9
        tags: start
    sPlungerButton:
        number: cabio-10
    sLowerRightPopBuper:
        number: pio2-24
        debounce: quick
    sUpperRightPopBumper:
        number: pio2-25
        debounce: quick
    sUpperLeftPopBumper:
        number: pio2-26
        debounce: quick
    sLowerLeftPopBumper:
        number: pio2-27
        debounce: quick
    sSinglePopTarget:
        number: pio2-28

coils:
    cBallTroughEject:
        number: pio1-2
        default_pulse_ms: 15
        platform_settings:
            recycle_ms: 10ms
            pwm2_ms: 15ms
    cLeftFlipperPower:
        number: pio1-1
        default_pulse_ms: 25
    cLeftFlipperHold:
        number: pio1-0
        allow_enable: true
    cRightFlipperPower:
        number: pio1-7
        default_pulse_ms: 25
    cRightFlipperHold:
        number: pio1-6
        allow_enable: true
    cLeftSling:
        number: pio1-4
        default_pulse_ms: 18
        platform_settings:
            recycle_ms: 40
    cRightSling:
        number: pio1-5
        default_pulse_ms: 18
        platform_settings:
            recycle_ms: 40
    cAutoPlunger:
        number: pio1-3

flippers:
    leftFlipper:
        main_coil: cLeftFlipperPower
        hold_coil: cLeftFlipperHold
        activation_switch: sLeftFlipperButton
        eos_switch: sLeftFlipperEOS
        use_eos: true
    rightFlipper:
        main_coil: cRightFlipperPower
        hold_coil: cRightFlipperHold
        activation_switch: sRightFlipperButton
        eos_switch: sRightFlipperEOS
        use_eos: true

ball_devices:
    bdTrough:
        ball_switches: sBall1,sBall2,sBall3,sBall4,sBall5,sBall6
        eject_coil: cBallTroughEject
        tags: trough, home, drain
        jam_switch: sBallJam
        eject_coil_jam_pulse: 15ms
        eject_targets: bdPlunger
    bdPlunger:
        ball_switches: sPlungerLane
        entrance_count_delay: 300ms
        eject_timeouts: 3s
        eject_coil: cAutoPlunger
        mechanical_eject: true
        player_controlled_eject_event: sPlungerButton_active

autofire_coils:
    right_kicker:
        coil: cRightSling
        switch: sRightSlingUpper
    right_kicker_lower:
        coil: cRightSling
        switch: sRightSlingLower
    left_kicker:
        coil: cLeftSling
        switch: sLeftSlingUpper
    left_kicker_lower:
        coil: cLeftSling
        switch: sLeftSlingLower

playfields:
    playfield:
        tags: default
        default_source_device: bdPlunger
    

        