#config_version=6

mode:
  start_events: start-mode-springManager
  stop_events: stop-mode-springManager
  priority: 175

variable_player:
  drop_target_leftCrystal_down:
    leftCrystalAttunement: 1
    dropTargetHits: 1
  drop_target_centerCrystal_down:
    centerCrystalAttunement: 1
    dropTargetHits: 1
  drop_target_rightCrystal_down:
    rightCrystalAttunement: 1
    dropTargetHits: 1
  drop_target_springEntry_down:
    springEntryCrystalAttunement: 1
    dropTargetHits: 1

show_player:
  drop_target_leftCrystal_down{current_player.leftCrystalAttunement<=1}:
    led_color:
      show_tokens:
        lights: leftUpperCrystalInsert
        color: 882222
  drop_target_leftCrystal_down{current_player.leftCrystalAttunement>=2}:
    led_color:
      show_tokens:
        lights: leftUpperCrystalInsert
        color: DD4444
  drop_target_centerCrystal_down{current_player.centerCrystalAttunement<=1}:
    led_color:
      show_tokens:
        lights: centerUpperCrystalInsert
        color: 222288
  drop_target_centerCrystal_down{current_player.centerCrystalAttunement>=2}:
    led_color:
      show_tokens:
        lights: centerUpperCrystalInsert
        color: 4444DD
  drop_target_rightCrystal_down{current_player.rightCrystalAttunement<=1}:
    led_color:
      show_tokens:
        lights: rightUpperCrystalInsert
        color: 888844
  drop_target_rightCrystal_down{current_player.rightCrystalAttunement>=2}:
    led_color:
      show_tokens:
        lights: rightUpperCrystalInsert
        color: DDDD44