#config_version=6

# This is the mode definition for tracking potion qualification

# The following is the mode config data
# It contains the start event, based on the defined start event,
# and corresponding stop event.  The priority is 600 for this mode
mode:
  start_events: start-mode-potionQualifier
  stop_events: stop-mode-potionQualifier
  priority: 600

# The following defines the player variable changes for this mode.
variable_player:

  # Player Variable Names are defined in this mode in two ways, as
  # an increment via call
  #
  # Event Calling the Change in Variable:
  #   Player Variable: Amount to Change By
  #
  # The other way it is changed is by an action as such:
  #
  # Event Calling the Change in Variable:
  #   Player Variable:
  #     Variable Type: Value for Action
  #     action: Type of Action to be peformed
  sCauldronLeftSpinner_active:
    leftFireLevel: 1
    potionSpinners: 1
  sCauldronRightSpinner_active:
    rightFireLevel: 1
    potionSpinners: 1
  mode_potionQualifier_started:
    leftFireLevel:
      int: 0
      action: set
    rightFireLevel:
      int: 0
      action: set

# The following Defines the events that will be called from this mode
event_player:

  # Events are defined as follows:
  # Name of Event to Listen For:
  #   - Name of Event to Call After Listened Event Occurs{Conditional Statement} 
  sCauldronLeftSpinner_active:
    - start-mode-potionSelection{current_player.leftFireLevel>=20 and current_player.rightFireLevel>=20}
  sCauldronRightSpinner_active:
    - start-mode-potionSelection{current_player.leftFireLevel>=20 and current_player.rightFireLevel>=20}
